# Generated by Django 5.2.4 on 2025-07-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('company', 'Company'), ('applicant', 'Applicant')], default='Choose Role', max_length=10),
        ),
    ]
