# Generated by Django 5.2.4 on 2025-07-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('company', 'Company'), ('applicant', 'Applicant')], default='applicant', max_length=10),
        ),
    ]
