# Generated by Django 5.2.4 on 2025-08-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_application_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
    ]
