# Generated by Django 5.2.4 on 2025-08-03 07:21

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_application_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(default='sample_resume.pdf', upload_to='resumes/', validators=[jobs.models.validate_resume]),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default='Nagotiable', max_length=150),
        ),
    ]
