# Generated by Django 5.2.4 on 2025-08-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_max_salary_job_min_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
