# Generated by Django 5.2.4 on 2025-08-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
    ]
