# Generated by Django 5.2.4 on 2025-08-15 09:20

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(default='resumes/sample_resume.pdf', upload_to='resumes/', validators=[jobs.models.validate_resume]),
        ),
    ]
